version: '3.4'

services:
  stackoverflowtags.api:
    image: ${DOCKER_REGISTRY-}stackoverflowtagsapi
    container_name: stackoverflowtags.api
    build:
      context: .
      dockerfile: StackOverflowTags.api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      stackoverflowtags.database:
        condition: service_healthy
    links:
      - stackoverflowtags.database

  stackoverflowtags.database:
    image: postgres:latest
    container_name: stackoverflowtags.database
    environment:
      - POSTGRES_DB=sotags
      - POSTGRES_USER=sotagsuser
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/stackoverflowtags-db:/var/lib/postgresql/data
    ports:
      -  5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sotagsuser"]
      interval: 5s
      timeout: 5s
      retries: 5
      